/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phase1_Main */

#ifndef _Included_phase1_Main
#define _Included_phase1_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     phase1_Main
 * Method:    urunKaydet
 * Signature: ()Lphase1/Product;
 */
JNIEXPORT jobject JNICALL Java_phase1_Main_productReg();
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
