/* DO NOT EDIT THIS FILE - it is machine generated */
#include "C:\Program Files\Java\jdk-14.0.2\include\jni.h"
#include "C:\Program Files\Java\jdk-14.0.2\include\win32\jni_md.h"
/* Header for class phase1_Main */

#ifndef _Included_phase1_Main
#define _Included_phase1_Main
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     phase1_Main
	 * Method:    productReg
	 * Signature: ()Lphase1/Product;
	 */
	JNIEXPORT jobject JNICALL Java_phase1_Main_productReg
	(JNIEnv*, jobject);

	/*
	 * Class:     phase1_Main
	 * Method:    productSend
	 * Signature: ()Lphase1/Product;
	 */
	JNIEXPORT jobject JNICALL Java_phase1_Main_productSend
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
